opa-dockerfile-policy

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -47,7 +47,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Set up JDK 17 and cache Maven
-        uses: actions/setup-java@v4`
+        uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
@@ -148,7 +148,21 @@ jobs:
   # ------------------ Opa Docker Security Check ------------------
 
 
-
+  validate:
+    runs-on: ubuntu-latest
+    needs: [test, mutation-test]
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Run OPA security check on Dockerfile
+        run: |
+          if [ -f Dockerfile ]; then
+            echo "Running OPA security check on Dockerfile..."
+            docker run --rm -v $(pwd):/policy openpolicyagent/conftest:latest test Dockerfile --policy opa-docker-security.rego
+          else
+            echo "Dockerfile not found!"
+            exit 1
+          fi
 
 
   # ------------------ Docker Build & Push to ECR ------------------
